# Generated by Django 4.2 on 2023-04-16 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_description_product_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='item',
            new_name='category',
        ),
    ]
